<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="NoticeTest" skipped="1" failures="0" errors="0" tests="9" assertions="23" time="0.08394100051373243">
  <testcase name="test_update_valid_sent_at_validator" classname="NoticeTest" assertions="2" time="0.019241000059992075">
  </testcase>
  <testcase name="test_notice1" classname="NoticeTest" assertions="2" time="0.007457000203430653">
  </testcase>
  <testcase name="test_validator_must_be_in_the_future" classname="NoticeTest" assertions="5" time="0.00789300026372075">
  </testcase>
  <testcase name="test_invalid_chonic" classname="NoticeTest" assertions="2" time="0.008320000022649765">
  </testcase>
  <testcase name="test_schedule_next_notice" classname="NoticeTest" assertions="0" time="0.0004990003071725368">
    <skipped type="test_schedule_next_notice"/>
  </testcase>
  <testcase name="test_soonest_valid" classname="NoticeTest" assertions="5" time="0.03215699968859553">
  </testcase>
  <testcase name="test_my_helper" classname="NoticeTest" assertions="1" time="0.0002749999985098839">
  </testcase>
  <testcase name="test_update_INVALID_sent_at_validator" classname="NoticeTest" assertions="2" time="0.003677000291645527">
  </testcase>
  <testcase name="test_update_nil_sent_at_validator" classname="NoticeTest" assertions="4" time="0.004421999678015709">
  </testcase>
</testsuite>
